name: Link Check
on:
  push:
    branches: [ main ]
  pull_request:

permissions:
  contents: read

jobs:
  lychee:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Offline mode = check only local/internal links in your repo.
      # This avoids false reds from external sites timing out.
      - name: Run lychee (offline)
        uses: lycheeverse/lychee-action@v1
        with:
          args: >
            --offline
            --exclude-mail
            --no-progress
            .
