name: Generate sitemap

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Generate sitemap.xml
        run: |
          echo '<?xml version="1.0" encoding="UTF-8"?>' > sitemap.xml
          echo '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">' >> sitemap.xml
          echo '  <url><loc>https://www.kosconn.com/</loc></url>' >> sitemap.xml
          echo '  <url><loc>https://www.kosconn.com/services.html</loc></url>' >> sitemap.xml
          echo '  <url><loc>https://www.kosconn.com/about.html</loc></url>' >> sitemap.xml
          echo '  <url><loc>https://www.kosconn.com/how-we-work.html</loc></url>' >> sitemap.xml
          echo '  <url><loc>https://www.kosconn.com/resources.html</loc></url>' >> sitemap.xml
          echo '  <url><loc>https://www.kosconn.com/contact.html</loc></url>' >> sitemap.xml
          echo '</urlset>' >> sitemap.xml

      - name: Upload sitemap artifact
        uses: actions/upload-artifact@v3
        with:
          name: sitemap
          path: sitemap.xml

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
