name: Generate sitemap
on: [push]
jobs:
  sitemap:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          cat > sitemap.xml <<'EOF'
          <?xml version="1.0" encoding="UTF-8"?>
          <urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
            <url><loc>https://www.kosconn.com/</loc></url>
          </urlset>
          EOF
      - uses: EndBug/add-and-commit@v9
        with:
          add: 'sitemap.xml'
          message: 'chore: update sitemap'
